language: go
go:
  - "1.11"

os:
  - linux
  # - osx

before_install:
  - sudo apt-get install -y gnome-keyring libsecret-common
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script:
  - dep ensure
