name: test

on: [push, pull_request]

jobs:
  test-matrix:

    strategy:
      matrix:
        operating-system: [ubuntu-18.04, windows-2019]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@master

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'

      - name: Install Go deps
        run: |
          go get github.com/golangci/govet
          go get golang.org/x/lint/golint

      # - name: Install Taskfile
      #   uses: Arduino/actions/setup-taskfile@master

      - name: Build the CLI
        # run: task build
        run: go build

      - name: Run unit tests
        # run: task test-unit
        run: go test -v

      - name: Send unit tests coverage to Codecov
        # Since secrets aren't available on forks, we only
        # upload coverage on `push`. This might change if
        # Codecov whitelists GitHub, lifting the need
        # for a token.
        if: >
          matrix.operating-system != 'windows-2019' &&
          github.event_name == 'push'
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage_unit.txt
          flags: unit
